{% set version = "0.6.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-visdat
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/visdat_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/visdat/visdat_{{ version }}.tar.gz
  sha256: 104acdbb9d41167b861ab24de0e1e1e14f61c1b476bac112fcbc6e47c157e598

build:
  merge_build_host: true  # [win]
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-cli
    - r-dplyr
    - r-forcats
    - r-ggplot2
    - r-glue
    - r-magrittr
    - r-purrr
    - r-readr
    - r-scales
    - r-tibble
    - r-tidyr
  run:
    - r-base
    - r-cli
    - r-dplyr
    - r-forcats
    - r-ggplot2
    - r-glue
    - r-magrittr
    - r-purrr
    - r-readr
    - r-scales
    - r-tibble
    - r-tidyr

test:
  commands:
    - $R -e "library('visdat')"           # [not win]
    - "\"%R%\" -e \"library('visdat')\""  # [win]

about:
  home: https://docs.ropensci.org/visdat/
  dev_url: https://github.com/ropensci/visdat
  license: MIT
  summary: Create preliminary exploratory data visualisations of an entire  dataset to identify problems or unexpected features using 'ggplot2'.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - philip-khor

# Date/Publication: 2019-02-15 15:30:03 UTC
