{% set version = "0.5.3" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-visdat
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/visdat_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/visdat/visdat_{{ version }}.tar.gz
  sha256: 527c76b6643b8475a58516763ef40238cdc61ec62d2dcf690f7c316b93b878c6

build:
  merge_build_host: true  # [win]
  number: 1003
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-dplyr
    - r-ggplot2
    - r-glue
    - r-magrittr
    - r-purrr
    - r-readr
    - r-tibble
    - r-tidyr
  run:
    - r-base
    - r-dplyr
    - r-ggplot2
    - r-glue
    - r-magrittr
    - r-purrr
    - r-readr
    - r-tibble
    - r-tidyr

test:
  commands:
    - $R -e "library('visdat')"           # [not win]
    - "\"%R%\" -e \"library('visdat')\""  # [win]

about:
  home: http://visdat.njtierney.com/, https://github.com/ropensci/visdat
  license: MIT
  summary: Create preliminary exploratory data visualisations of an entire  dataset to identify problems or unexpected features using 'ggplot2'.
  license_family: MIT

  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE
extra:
  recipe-maintainers:
    - conda-forge/r
    - philip-khor

# Package: visdat
# Title: Preliminary Visualisation of Data
# Version: 0.5.3
# Authors@R: c( person("Nicholas", "Tierney", role = c("aut", "cre"), email = "nicholas.tierney@gmail.com",  comment = c(ORCID = "https://orcid.org/0000-0003-1460-8722")), person("Sean", "Hughes", role = "rev",  comment =c(ORCID = "https://orcid.org/0000-0002-9409-9405", "Sean Hughes reviewed the package for rOpenSci,  see https://github.com/ropensci/onboarding/issues/87")), person("Mara", "Averick", role = "rev",  comment = "Mara Averick reviewed the package for rOpenSci, see  https://github.com/ropensci/onboarding/issues/87"), person("Stuart", "Lee", role = c("ctb")), person("Earo", "Wang", role = c("ctb")), person("Nic", "Crane", role = c("ctb")) )
# Description: Create preliminary exploratory data visualisations of an entire  dataset to identify problems or unexpected features using 'ggplot2'.
# Depends: R (>= 3.2.2)
# License: MIT + file LICENSE
# LazyData: true
# RoxygenNote: 6.1.1
# Imports: ggplot2, tidyr, dplyr, purrr, readr, magrittr, stats, tibble, glue
# URL: http://visdat.njtierney.com/, https://github.com/ropensci/visdat
# BugReports: https://github.com/ropensci/visdat/issues
# Suggests: testthat, plotly (>= 4.5.6), knitr, rmarkdown, vdiffr, gdtools, spelling
# VignetteBuilder: knitr
# Encoding: UTF-8
# Language: en-US
# NeedsCompilation: no
# Packaged: 2019-02-15 02:57:38 UTC; ntie0001
# Author: Nicholas Tierney [aut, cre] (<https://orcid.org/0000-0003-1460-8722>), Sean Hughes [rev] (<https://orcid.org/0000-0002-9409-9405>, Sean Hughes reviewed the package for rOpenSci, see https://github.com/ropensci/onboarding/issues/87), Mara Averick [rev] (Mara Averick reviewed the package for rOpenSci, see https://github.com/ropensci/onboarding/issues/87), Stuart Lee [ctb], Earo Wang [ctb], Nic Crane [ctb]
# Maintainer: Nicholas Tierney <nicholas.tierney@gmail.com>
# Repository: CRAN
# Date/Publication: 2019-02-15 15:30:03 UTC
