appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: mAoFVPQqaZSf3Vv/zAZPcPScOBqIXQlmqWszJHS017+EU3MjnXEci100/JufC1DlgbgiqX/uwQkG+9kXBRygx4VEm1c6TaT6sxUVOcakrAjj+q2HQSFMEhx5ba+tTonbPCSFKxZLximKHV60pP1j1C/EwV0LT8aKkqj7qswb0rSK5Gz1WtqbdwLMwkopVk3aWAuVIAn4ur6FZpjSRFZjrwumTsADlOhb4cWEAjB6a+GU08eqBWBGV6EGO379AWWcge9ku+cKcuPWfEPCzo5Ie5J0PtMc6AM3PhhV6uAcHIRCUEhlKfaAXVpkMYMwhL/NHMtj+xBcGbKpUIfDIU/isVKufW5LjPwtg2MtzY+sk3xtO4XEdZ8nxSqeSKZjmc2hK+rN68k7wiIFiLRN+1sexSfnUFpcTx8wl2AZURMGKEA9EXf11xjcMBvFAxROVwnVmFXXCj1F1LplGmgXgVWrnG5Xq3RejtK6ziTrlMxtbmeFkAus/fF/Ox1CcFBzXzySwdpYIkH6MRzMCQ7u+uNbyxfKqbKxJPwIw3CMNv41i6OPxUdbVU6CxwHcbxk1e/l1GDEJyg6BtT8TTMjE1dclnXFtPMsZmiJMT+GcPsiD7M8a7hen4eyXu+tdJ0y0aLxlpS9t9JFY652YAoNsxZ9lUOBVSq3rMx+/0iO/0Lqrlhc=}
